version: "3"

services:
  postgres:
    image: postgres:11.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - ${POSTGRE_PORT}:${POSTGRE_PORT}
    volumes: [./DB/sql/:/docker-entrypoint-initdb.d]
